language: node_js
node_js:
- '8'
install:
- npm i
script:
- npm audit
branches:
  only:
  - master
cache:
  directories:
  - node_modules
# deploy:
# - provider: npm
#     email: iamdevlinph@gmail.com
#     skip-cleanup: true
#     on:
#       tags: true
#     api_key:
#       secure: Aek9s5X4ailjc0qnkGtEnIA+nLuM9+4twCYZuIijtlSfDt6DtuxIAD6LFeHoprT0tjYhS4xKdcbahs8K2XN++6rYJne2vSWklhNvyb7e3vMBRC7CRs3KHox2M6nawzL1qkvEnTiM4sEu1JRJQchUyOSv+zFkvZgLEAooU8+/d/uePa5eW4GEtDqmWJC0uus3JKj7r4jWFJY1xDH9GSbTvZOGuYjzO9pr5YAZRnIvaXFkF3XP5kvrh7aGH4o/PyQtZdvmh3c3wcvzNLS+W8vf45n5GnYANPEwmV8DvFCveABAjPkEPO0qYal9TugSqU+CGmdTC1N9jGyUdaKisQM8aBvc1JqhGihQ2SfrrLBZc7e1g8vdk36TyLXm6hxPTReE4pZDg5N0VFINAa8SKE6OJepuGOdIiqciWfgD6L001J348k8iVewkbGx9YAIMpi3RnLkHi4Bbd9tCja4EWJeFj3/Ar9nZJc+Bj0mQrvVZRFWo3FicKpKmFGlcRR5NbgkZPKROxFDQuhLAZloBDJv509PMnRWWMUyLSXmdUBS9AxQNmw9WUkdneSuP+ho6NUVK6jniOIRUL8IO3ktPOTFMl/XR3OLZDYHuaQ9p57XrKVF0uq64mQnq0MZWheoYpPhzqdjjR/gHXs9BctewFI3DawIbuV9zNuqDFrR0kLmrDdI=
